org.gradle.jvmargs=-Xmx2048M -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=false
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# NEW RULES: Force Kotlin to share memory and not spawn a new process
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.jvm.options=-Xmx1024M